### ISSUE TITLE
[Governing bodies] Registered user can download documents from 'Крайовий Провід Пласту'' page

### ISSUE THREAD

**Issue by setorianadya** [ita-social-projects/EPlast#1919]
**Environment:** Windows 10 Pro 20H2, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit).
**Reproducible:** always
**Priority:** medium.
**Severity:** minor.
**Build found:** d60c204

**Preconditions:**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as a registered user

**Steps to reproduce**

1. Go to 'Крайовий Провід Пласту'' by link (https://eplast.westeurope.cloudapp.azure.com/regionsBoard)
2. Press the button "Більше" in "Документообіг" field
3. Try to download documents

**Actual result**
Registered user can download documents from on 'Крайовий Провід Пласту'' page

**Expected result**
Registered users can't download documents. Actually, he can`t see button "Більше" in "Документообіг" field

**Comment by setorianadya** [comment]
The same for Governing Body`s sector

**Comment by ChrystynaKubai** [comment]
Step 2 should not done in 'Steps to Redproduce' according to Access Level of the registered user in the table 'Regional Board of the Plast'.
The label '3' next to 'Документообіг' should not available.

**Comment by MariyaKonsevych** [comment]
**Build**: [4ad6f9a]
The bug is reproduced on the browsers: **Google Chrome Версія 101.0.4951.54** (Розробка) (64-розрядна версія)
Log in as an **Adherent** (Прихильник)

**Actual result**
Adherent (Прихильник) can download documents from on page'Крайовий Провід Пласту''.

**Expected result**
Adherent (Прихильник) can't download documents. Actually, he can't see the button "Більше" in the field "Документообіг".

![2022-05-05 13_10_13-EPlast](https://user-images.githubusercontent.com/104513228/167423271-1f339897-ce1c-4b27-bcf6-c08d50eda07f.png)
![2022-05-05 13_16_02-EPlast](https://user-images.githubusercontent.com/104513228/167423290-8a197dbf-cbd7-48ce-aea8-2e12980973fe.png)
