### ISSUE TITLE
[Cities] [Delegation/Поручення] The Village Admin can give a guarantee for members not from his city or regions

### ISSUE THREAD

**Issue by SofiiaYavorivska** [ita-social-projects/EPlast#2011]
**Environment:** Windows 10(x64), Google Chrome Version 95.0.4638.54
**Reproducible:** always
**Priority:** medium
**Severity:** minor
**Build found:** 077fea7

**Preconditions**
Go to https://eplast.westeurope.cloudapp.azure.com/signin
Log in as a City Admin

**Steps to reproduce**
1. Go to the 'User table' page
2. Select any user, who is not in your сity or regions
3. Go to the 'Delegation' tab
4. Add the delegation
5. Pay attention to the message "Delegation successfully created"

**Actual result**
The Village Admin can give a guarantee for members not from his city or regions

https://user-images.githubusercontent.com/92793418/140358569-481efaa5-c5a0-4dda-9616-233c27b80cb3.mp4

**Expected result**
The Village Admin can not give a guarantee for members not from his city or regions

**Comment by Hrystyna96** [comment]
The Village Admin can still give a guarantee for members not from his city or regions.

**Comment by ystrotska** [comment]
The bug is fixed when the city admin assigns "поруки" from the Users table.
Please note the bug is still reproduced when the city admin assigns "поруки" from the left-side menu "Станиці", choosing any user from another city or region.
![village admin](https://user-images.githubusercontent.com/104917914/193790207-d50a6389-9e72-411c-8f24-93b99ca8bdbe.jpg)
![поручення](https://user-images.githubusercontent.com/104917914/193790258-08aaffa3-2c6d-476f-ae17-cca02f4f4192.jpg)

**Comment by Mykola123-NMT** [comment]
> The bug is fixed when the city admin gives a guarantee from the Users table. Please note the bug is still reproduced when the city admin gives a guarantee from the left-side menu "Станиці", choosing any user from another city or region. ![village admin](https://user-images.githubusercontent.com/104917914/193790207-d50a6389-9e72-411c-8f24-93b99ca8bdbe.jpg) ![поручення](https://user-images.githubusercontent.com/104917914/193790258-08aaffa3-2c6d-476f-ae17-cca02f4f4192.jpg)

Here user can approve because he is 'Дійсний член', but not because he is city admin.
