### ISSUE TITLE
[Registration page] Absence of error message when entering too short data into password field

### ISSUE THREAD

**Issue by IhorQC523** [ita-social-projects/EPlast#345]
[https://jira.softserve.academy/browse/NETLV-99](url)

Priority: Low
Severity: Trivial 
Environment: MacOS High Sierra 10.13.6, Firefox Browser 77.0.1 (64-bit)

Steps to reproduce:

    1. Go to https://eplast.azurewebsites.net/ website
    2. Click on 'Зареєструватись' tab
    3. Enter too short value into password field (e.g. Aaa123!)

Actual result:

The field filled with data. There is no any error message.

Expected result:

Error message 'Пароль повинен містити щонайменше 8 символів

**Comment by Oksana-lviv** [comment]
Incorrect message is displayed 'Мінімально допустима довжина - 6 символів'. Due to User Story [NETLV-99]  it should be 'Пароль' must be at least 8 characters, must contain letters, numbers and reserved characters (=,/, |, \, *, (, ), _, :, ;, #, %, ^, ?, [, ]) (mandatory field).
![bug-ver-fail345](https://user-images.githubusercontent.com/71265495/95067703-dd602600-070c-11eb-9915-866b8a1b7847.jpg)
@ViktorKalynenko

**Comment by Iravozna** [comment]
There is inconsistency in an error message about length of password:
Log in page - 6 characters
Registration page - 8 characters. 
Password must be at least 8 characters on both pages. ,
characters
