### ISSUE TITLE
[Awards Page] There is no error message about limit characters when adding a new type of 'Відзначення'

### ISSUE THREAD

**Issue by NataRomm** [ita-social-projects/EPlast#452]
**Summary:** [Awards Page] There is no error message about limit characters when adding a new type of 'Відзначення'

**Test Data**
Назва типу відзначення: 1111111111111111111111111111111111111111111111111111111111112222222222222222222222222222222222222222222222222222222222222222222222222222333333333333333333333333333333333333333333333333333333333333333333333333333555566666666666666666666666666666666677

**Pre-Conditions:**
- Open the application and register into a system as a Region Administrator.
- Choose the 'Відзначення' tab.

**Steps to Reproduce:**
- Click on the 'Редагування типів відзначень' button
- Type in the 'Назва типу відзначення' field data from the test data (250 characters)
- Continue type any character in the 'Назва типу відзначення' field

**Actual Result:**
There is no possibility to continue type in this field anything
**Expected Result:**
The error message is below the field: 'Максимальна довжина - 250 символів!'

**Attachments:**
Actual.png
![image](https://user-images.githubusercontent.com/50527578/95068961-b571c200-070e-11eb-8910-114b0c62ae3a.png)

Expected.png
![image](https://user-images.githubusercontent.com/50527578/95069143-f23db900-070e-11eb-8ebb-9ffa7225d006.png)

**Environment:** 
OS Windows, Version 10 Pro
Browser Google Chrome, Version 84.0.4147.89
**Data and Time:** 5.10.20 at 13:00
**Tester:** Nataliya Romanyuk

**Severity:** Low
**Priority:** Medium

**Comment by MykytaKlymachkov** [comment]
Can't reproduce, type of the field changed and no there is no possibility to add new value

**Comment by MykytaKlymachkov** [comment]
Can't paste test data into the 'Редагувати відзначення' text field.
Max symbols amount valid in this field is 248, and it is not possible to type more than that. 
Still this bug is very low priority and severity because most of awards are premade and doesn't consist of such amount of characters
![Screenshot_51](https://user-images.githubusercontent.com/72553191/97846577-e0900700-1cf6-11eb-81ab-a82ae536e8c6.jpg)
![Screenshot_52](https://user-images.githubusercontent.com/72553191/97846579-e1c13400-1cf6-11eb-92b7-5557787e7a61.jpg)
![Screenshot_53](https://user-images.githubusercontent.com/72553191/97846583-e259ca80-1cf6-11eb-8dea-eaa91e5a650b.jpg)

**Comment by OlenaTomashevska** [comment]
No error message: 'Максимальна довжина - 250 символів!' underneath the text field.
![No error message](https://user-images.githubusercontent.com/72553215/99711582-9ce51d80-2aaa-11eb-97ab-aadcb6c874f2.png)
